# Generated by Django 2.1.1 on 2018-10-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=30)),
                ('game_subtitle', models.CharField(max_length=30)),
                ('game_image', models.CharField(max_length=30)),
                ('game_dateimported', models.DateField()),
                ('game_minpersons', models.IntegerField()),
                ('game_maxpersons', models.IntegerField()),
                ('game_minteams', models.IntegerField()),
                ('game_maxteams', models.IntegerField()),
                ('game_minfacilitators', models.IntegerField()),
                ('game_timeneeded', models.CharField(max_length=30)),
                ('game_environment', models.CharField(max_length=30)),
                ('game_materials', models.CharField(max_length=30)),
                ('game_portable', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics_epikoinwnia', models.BooleanField()),
                ('topics_synergasiaomadikotika', models.BooleanField()),
                ('topics_hgesia', models.BooleanField()),
                ('topics_debrief', models.BooleanField()),
                ('topics_anatrofodotisi', models.BooleanField()),
                ('topics_atypiaxiologogisi', models.BooleanField()),
                ('topics_icebreaker', models.BooleanField()),
                ('topics_energiser', models.BooleanField()),
                ('topics_closing', models.BooleanField()),
                ('topics_creativethought', models.BooleanField()),
                ('topics_organwsiergasias', models.BooleanField()),
                ('topics_prosdokies', models.BooleanField()),
                ('topics_stoxasmos', models.BooleanField()),
                ('topics_stress', models.BooleanField()),
                ('topics_analysiprovlimatwn', models.BooleanField()),
                ('topics_diapragmatefsis', models.BooleanField()),
                ('topics_diaxeirisiallagwn', models.BooleanField()),
                ('topics_empistosyni', models.BooleanField()),
                ('topics_egraleio', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_subjects',
            field=models.ManyToManyField(to='personal.Topics'),
        ),
    ]
