# Generated by Django 2.1.1 on 2018-10-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(max_length=30, verbose_name='Τίτλος'),
        ),
    ]
