# Generated by Django 2.1.1 on 2018-10-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20181013_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_dateimported',
            field=models.DateField(verbose_name='Ημερομηνία Ένταξης'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_environment',
            field=models.CharField(max_length=30, verbose_name='Τόπος εκπαίδευσης'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.FilePathField(verbose_name='Εικόνα'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_materials',
            field=models.CharField(max_length=30, verbose_name='Υλικά που απαιτούνται'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_maxpersons',
            field=models.IntegerField(verbose_name='Μέγιστος αρ. ατόμων'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_maxteams',
            field=models.IntegerField(verbose_name='Μέγιστος αρ. ομάδων'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_minfacilitators',
            field=models.IntegerField(verbose_name='Αριθμός ελάχιστων Facilitators'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_minpersons',
            field=models.IntegerField(verbose_name='Ελάχιστος αρ. ατόμων'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_minteams',
            field=models.IntegerField(verbose_name='Ελάχιστος αρ. ομάδων'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_portable',
            field=models.CharField(max_length=30, verbose_name='Φορητότητα'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_subjects',
            field=models.ManyToManyField(to='personal.Topics', verbose_name='Θεματολογια'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_subtitle',
            field=models.CharField(max_length=30, verbose_name='Υπότιτλος'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_timeneeded',
            field=models.CharField(max_length=30, verbose_name='Ελάχιστος χρόνος'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_analysiprovlimatwn',
            field=models.BooleanField(verbose_name='Ανάλυση & Επίλυση Προβλημάτων'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_anatrofodotisi',
            field=models.BooleanField(verbose_name='Ανατροφοδότηση'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_atypiaxiologogisi',
            field=models.BooleanField(verbose_name='Άτυπη Αξιολόγηση'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_closing',
            field=models.BooleanField(verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_creativethought',
            field=models.BooleanField(verbose_name='Ανάπτυξη Δημιουργικής Σκέψη'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_debrief',
            field=models.BooleanField(verbose_name='Debrief'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_diapragmatefsis',
            field=models.BooleanField(verbose_name='Διαπραγματεύσεις'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_diaxeirisiallagwn',
            field=models.BooleanField(verbose_name='Διαχείριση Αλλαγών'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_egraleio',
            field=models.BooleanField(verbose_name='Εργαλείο Εκπαιδευτικής Διεργασίας'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_empistosyni',
            field=models.BooleanField(verbose_name='Εμπιστοσύνη'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_energiser',
            field=models.BooleanField(verbose_name='Energizer'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_epikoinwnia',
            field=models.BooleanField(verbose_name='Επικοινωνία'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_hgesia',
            field=models.BooleanField(verbose_name='Ηγεσία'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_icebreaker',
            field=models.BooleanField(verbose_name='Icebreaker'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_organwsiergasias',
            field=models.BooleanField(verbose_name='Οργάνωση Εργασίας'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_prosdokies',
            field=models.BooleanField(verbose_name='Προσδοκίες'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_stoxasmos',
            field=models.BooleanField(verbose_name='Στοχασμός'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_stress',
            field=models.BooleanField(verbose_name='Στρές'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_synergasiaomadikotika',
            field=models.BooleanField(verbose_name='Συνεργασία & Ομαδικότητα'),
        ),
    ]
