# Generated by Django 2.1.1 on 2018-10-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20181013_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Topics', verbose_name='Θεματολογια'),
        ),
    ]
