# Generated by Django 2.1.1 on 2018-10-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_auto_20181013_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_subjects',
        ),
        migrations.AddField(
            model_name='game',
            name='game_subjects',
            field=models.ManyToManyField(to='personal.Topics', verbose_name='Θεματολογια'),
        ),
    ]
