# Generated by Django 2.1.1 on 2018-10-12 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20181013_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topics_analysiprovlimatwn',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_anatrofodotisi',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_atypiaxiologogisi',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_closing',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_creativethought',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_debrief',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_diapragmatefsis',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_diaxeirisiallagwn',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_egraleio',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_empistosyni',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_energiser',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_hgesia',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_icebreaker',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_organwsiergasias',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_prosdokies',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_stoxasmos',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_stress',
        ),
        migrations.RemoveField(
            model_name='topics',
            name='topics_synergasiaomadikotika',
        ),
    ]
