# Generated by Django 2.1.1 on 2018-10-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20181013_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topics_epikoinwnia',
        ),
        migrations.AddField(
            model_name='topics',
            name='topics_entry',
            field=models.CharField(default=2, max_length=50, verbose_name='Μεθοδολογία'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_subjects',
        ),
        migrations.AddField(
            model_name='game',
            name='game_subjects',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.Topics', verbose_name='Θεματολογια'),
            preserve_default=False,
        ),
    ]
