# Generated by Django 2.1.1 on 2018-10-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20181013_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='topics_anotherfield',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Πεδίο'),
        ),
        migrations.AddField(
            model_name='topics',
            name='topics_dateimported',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Πεδίο2'),
        ),
    ]
