# Generated by Django 2.1.1 on 2018-10-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_auto_20181013_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics',
            name='topics_dateimported',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_subjects',
        ),
        migrations.AddField(
            model_name='game',
            name='game_subjects',
            field=models.ManyToManyField(to='personal.Topics', verbose_name='Θεματολογια'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_anotherfield',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='topics_entry',
            field=models.CharField(max_length=30, verbose_name='Μεθοδολογία'),
        ),
    ]
