# Generated by Django 2.1.1 on 2018-10-13 18:39

from django.db import migrations


class Migration(migrations.Migration):
	atomic = False
	dependencies = [
		('personal', '0011_auto_20181013_2124'),
	]

	operations = [
		migrations.RenameModel(
			old_name='Topics',
			new_name='Topic',
		),
		migrations.RenameField(
			model_name='topic',
			old_name='topics_anotherfield',
			new_name='topic_anotherfield',
		),
		migrations.RenameField(
			model_name='topic',
			old_name='topics_entry',
			new_name='topic_entry',
		),
	]
