# Generated by Django 2.1.1 on 2018-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_auto_20181014_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_image',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Εικόνα'),
        ),
    ]
