# Generated by Django 2.1.1 on 2018-10-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0014_auto_20181014_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_link',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Οδηγίες'),
        ),
    ]
