# Generated by Django 2.1.1 on 2018-10-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0015_auto_20181014_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_subtitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Υπότιτλος'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_title',
            field=models.CharField(blank=True, max_length=60, verbose_name='Τίτλος'),
        ),
    ]
